---
title: "Mean WT heights"
author: "Amanda Pennino"
date: "12/16/2020"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
```

##LATWAG wells
```{r}
#Missing from list: 52_4_d2, 86_2_s1, 43_3_s3, 42_4_s3
NAMES = list('42_2_s1','42_3_s1','42_3_s2','42_4_s1','42_4_s2','42_4_d1','42_4_d2','52_2_s1','52_3_s1','52_3_s2','52_3_s3','52_4_s1','52_4_s2','52_4_s3','52_4_d1','86_3_s1', '86_3_s2', '86_3_s3','86_4_s1', '86_4_s2', '86_4_s3')


wellDatasList <- list()

#Where the data is
userFilePath <- "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/"
setwd(paste0(userFilePath, "Aggregated_10min"))
for (well in NAMES){
  wellDatasList[[well]] <- read_csv(paste(well,"csv", sep = "."))
}


#add the well name column for each well's data table
i <- 1
wellsWNamesList <- list()
for (well in wellDatasList){
  wellsWNamesList[[i]] <- well %>% mutate(Well = NAMES[[i]])
  i <- i + 1
}



#one table
allWellData <- do.call(rbind, wellsWNamesList)


```

##Additional LATWAG wells:
```{r}
WT_423s3 <- read.csv("~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/Aggregated_10min/42_3_s3.csv")
WT_423s3$Well <- "42_3_s3"
WT_424s3 <- read.csv("~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/Aggregated_10min/42_4_s3.csv")
WT_424s3$Well <- "42_4_s3"

laggers <- rbind(WT_423s3, WT_424s3)
LATWAGwells <- rbind(allWellData, laggers)

#Why are there negative values?
LATWAGwells$Water.Level[LATWAGwells$Water.Level <= 0] <- NA
  
```

```{r}
NAMES = list('A5', 'A6', 'A7', 'D1', 'H4', 'I3', 'I6', 'I7', 'I8', 'I9', 'JD01', 'JD02', 'JD03', 'JD04', 'JD05', 'JD06', 'JD07', 'JD08', 'JD10', 'JD11', 'JD12', 'JD13', 'JD14', 'JD15', 'JD16', 'JD17', 'JD18', 'JD19', 'JD20', 'JD21', 'JD22', 'JD23', 'JD24', 'JD25', 'JD26', 'JD27', 'JD28', 'JD29', 'JD30', 'JD31', 'K1', 'K10', 'K11', 'K1D', 'K4D', 'K4M', 'K4S', 'K5', 'K6D', 'K6S', 'K7D', 'K7S', 'K8', 'K9', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 'O2', 'P1', 'P2', 'Q1', 'Q2', 'T1')

wellDatasList <- list()

#Where the data is
userFilePath <- "~/Documents/VT/Data/Gannon/"
setwd(paste0(userFilePath, "HBEF_W3_WellDepth"))
for (well in NAMES){
  wellDatasList[[well]] <- read_csv(paste(well,"txt", sep = "."))
}


#add the well name column for each well's data table
i <- 1
wellsWNamesList <- list()
for (well in wellDatasList){
  wellsWNamesList[[i]] <- well %>% mutate(Well = NAMES[[i]])
  i <- i + 1
}

#one table
allWellDataJP <- do.call(rbind, wellsWNamesList)
wellInfo<- read_csv("~/Documents/VT/Data/Gannon/HBEF_W3_WellDepth/WellLocationsandPipeHt.csv")

#join well info to all well data
wellDataJoinedJP <- left_join(allWellDataJP, wellInfo, by = "Well")
##set values  > 168 and values = -99 to NA
wellDataJoinedJP$level <- replace(wellDataJoinedJP$level, wellDataJoinedJP$level > 168, NA)
wellDataJoinedJP$Water.Level <-  na_if(wellDataJoinedJP$level, -99)
  
#subtract pipe height from level
finalWellDataJP <- wellDataJoinedJP %>% mutate(Water.Level = Water.Level - PipeHt)
#finalWellData <- allWellData %>% mutate(date = ymd_hms(date))


```

##Take average depth to water table by well
```{r}
AVG_latwag <- LATWAGwells %>%
  group_by(Well) %>%
  summarise_at(.vars = vars(`Water.Level`), .funs = mean, na.rm = TRUE) 

AVG_JP <- finalWellDataJP %>%
  group_by(Well) %>%
  summarise_at(.vars = vars(`Water.Level`), .funs = mean, na.rm = TRUE) 

AVERAGES <- rbind(AVG_latwag, AVG_JP)

write_csv(AVERAGES, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/avgWT_allWells.csv")

```