---
title: "Time aggregation"
author: "Amanda Pennino"
date: "12/16/2020"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(zoo)
```

```{r}
WT_422s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_2_s1.csv") 
WT_423s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_3_s1.csv") 
WT_423s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_3_s2.csv") 
WT_423s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_3_s3.csv") 
WT_424s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_4_s1.csv") 
WT_424s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_4_s2.csv") 
WT_424s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_4_s3.csv") 
WT_424d1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_4_d1.csv") 
WT_424d2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/42_4_d2.csv") 
WT_522s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_2_s1.csv") 
WT_523s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_3_s1.csv") 
WT_523s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_3_s2.csv") 
WT_523s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_3_s3.csv") 
WT_524s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_4_s1.csv") 
WT_524s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_4_s2.csv") 
WT_524s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_4_s3.csv") 
WT_524d1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_4_d1.csv") 
#WT_524d1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/52_4_d2.csv") 
#WT_862s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_2_s1.csv")
WT_863s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_3_s1.csv")
WT_863s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_3_s2.csv")
WT_863s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_3_s3.csv")
WT_864s1 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_4_s1_JB.csv") 
WT_864s2 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_4_s2.csv") 
WT_864s3 = read_csv("~/Documents/VT/Data/Benton/TimeSeriesData/86_4_s3.csv") 

#Fix the weird nonsense with the first well's DateTime format.
WT_422s1 <- WT_422s1 %>% mutate(DateTime = mdy_hm(`Date Time`))
WT_422s1 <- WT_422s1[,-2]
names(WT_422s1)[4]<-"Date Time"

```

##Functions.
```{r}

agg <- function(x) {
  WT.zoo <- zoo(x$`Water Level`, order.by = x$`Date Time`)
  WT.agg <- aggregate(WT.zoo, time(WT.zoo) - as.numeric(time(WT.zoo)) %% 600, mean)
  df <- as.data.frame(WT.agg) 
  df$DateTime <- time(WT.agg) #create a date column
  rownames(df) <- NULL 
  df <- df[,c(ncol(df), 1:(ncol(df)-1))] #reorder columns so Date first
  names(df)[2]<-"Water.Level"
  return(df)
}


```


```{r}

WT_422s1 = agg(WT_422s1)
WT_423s1 = agg(WT_423s1) 
WT_423s2 = agg(WT_423s2) 
WT_423s3 = agg(WT_423s3) 
WT_424s1 = agg(WT_424s1) 
WT_424s2 = agg(WT_424s2) 
WT_424s3 = agg(WT_424s3) 
WT_424d1 = agg(WT_424d1) 
WT_424d2 = agg(WT_424d2) 
WT_522s1 = agg(WT_522s1) 
WT_523s1 = agg(WT_523s1) 
WT_523s2 = agg(WT_523s2) 
WT_523s3 = agg(WT_523s3) 
WT_524s1 = agg(WT_524s1) 
WT_524s2 = agg(WT_524s2) 
WT_524s3 = agg(WT_524s3) 
WT_524d1 = agg(WT_524d1) 
#WT_524d1 = agg(WT_524d1) 
#WT_862s1 = agg(WT_862s1)
WT_863s1 = agg(WT_863s1)
WT_863s2 = agg(WT_863s2)
WT_863s3 = agg(WT_863s3)
WT_864s1 = agg(WT_864s1) 
WT_864s2 = agg(WT_864s2) 
WT_864s3 = agg(WT_864s3) 

```


```{r}
write_csv(WT_422s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/422s1.csv")
write_csv(WT_423s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/423s1.csv") 
write_csv(WT_423s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/423s2.csv") 
write_csv(WT_423s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/423s3.csv") 
write_csv(WT_424s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/424s1.csv") 
write_csv(WT_424s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/424s2.csv") 
write_csv(WT_424s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/424s3.csv") 
write_csv(WT_424d1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/424d1.csv") 
write_csv(WT_424d2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/424d2.csv") 
write_csv(WT_522s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/522s1.csv") 
write_csv(WT_523s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/523s1.csv") 
write_csv(WT_523s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/523s2.csv") 
write_csv(WT_523s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/523s3.csv") 
write_csv(WT_524s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/524s1.csv") 
write_csv(WT_524s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/524s2.csv") 
write_csv(WT_524s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/524s3.csv") 
write_csv(WT_524d1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/524d1.csv") 
#WT_524d1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/524d1.csv") 
#WT_862s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/862s1.csv")
write_csv(WT_863s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/863s1.csv")
write_csv(WT_863s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/863s2.csv")
write_csv(WT_863s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/863s3.csv")
write_csv(WT_864s1, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/864s1.csv") 
write_csv(WT_864s2, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/864s2.csv") 
write_csv(WT_864s3, "~/Documents/VT/Data/MyData/Wells/TimeSeriesData/WaterLevels/864s3.csv") 

```

