---
title: "Water Levels"
author: "Amanda Pennino"
date: "2/18/2021"
output: html_document
---

```{r}

library(tidyverse)
library(lubridate)

```

```{r}
#read in well
#DATA <- read_csv("86_4_s3.csv")
#DATA <- read.csv("42_3_s3.csv")
#DATA <- read.csv("42_4_s1.csv")

#Convert to date time for 42_2_s1
#DATA$`Date Time` <- as.POSIXct(DATA$`Date Time`, format = "%m/%d/%Y %H:%M") 


DATA <- read_csv("42_2_s1.csv", col_types = cols(
  X1 = col_number(),
  `Date Time` = col_datetime(format = "%m/%d/%Y %H:%M"),
  `Water Level` = col_number(),
  `Water Temperature` = col_number()
))

#Convert to date time for 42_2_s1
#DATA$`Date Time` <- as.POSIXct(DATA$`Date Time`, format = "%m/%d/%Y %H:%M") 

#well depths
#DEPTHS <- read_csv("~/Documents/VT/Data/MyData/Wells/Well_info/Well_depths.csv")
  
#DEPTH <- subset(DEPTHS$depth, DEPTHS$well == "42_4_s1")

# DATA %>%
#   ggplot(aes(x = `Date Time`, y = `Water Level (meters)`)) +
#   geom_line() +
#   geom_hline(yintercept = 0, linetype="dashed", 
#                 color = "red", size=0.5) +
#   ylab("Water depth from surface (m)") +
#   ggtitle("E Podzol: 42_2_s1") +
#   theme_bw()

#42_3_s3, 42_4_s1
# DATA %>%
#   ggplot(aes(x = `Date.Time`, y = `Water.Level`)) +
#   geom_line() +
#   geom_hline(yintercept = 0, linetype="dashed",
#                 color = "red", size=0.5) +
#   ylab("Water depth from surface (m)") +
#   ggtitle("E Podzol: 42_2_s1") +
#   theme_bw()

DATA %>%
  ggplot(aes(x = `Date Time`, y = `Water Level (meters)`)) +
  geom_line() +
  geom_hline(yintercept = 0, linetype="dashed",
                color = "red", size=0.5) +
  ylab("Water depth from surface (m)") +
  ggtitle("E Podzol: 42_2_s1") +
  theme_bw()

```

Clean up CSVs that aren't reading in as tibbles.
```{r}

#col_types = c("text","numeric","date")
DATA <- read_csv("42_3_s3.csv", col_types = cols(
  X1 = col_number(),
  `Date Time` = col_datetime(format = "%m/%d/%y %H:%M"),
  `Water Level` = col_number(),
  `Water Temperature` = col_number()
))

DATA$`Water Level` <- as.numeric(DATA$`Water Level`)

write.csv(DATA, "42_3_s3_csv.csv")

```



```{r}
#Look to JPs code to pull from a folder based on name all at once
#write a function to do this



wellNames = list('42_3_s1', '42_3_s2', '42_3_s3')

#read in all csvs into a list, with each data table accessible by each well's name
wellDatasList <- list()

for (well in wellNames){
  wellDatasList[[well]] <- read_csv(paste(well, "csv", sep = "."), col_types = cols(
  X1 = col_number(),
  `Date Time` = col_datetime(format = "%m/%d/%y %H:%M"),
  `Water Level` = col_number(),
  `Water Temperature` = col_number()
))
}

i <- 1
wellsWNamesList <- list()
for (well in wellDatasList){
  wellsWNamesList[[i]] <- well %>% mutate(Well = wellNames[[i]])
  i <- i + 1
}

#make one master data table with all the wells
allWellData <- do.call(rbind, wellsWNamesList)

-agallWellData %>%
  ggplot(aes(x = `Date Time`, y = `Water Level`)) +
  geom_line() +
  geom_hline(yintercept = 0, linetype="dashed", 
                color = "red", size=0.5) +
  ylab("Water depth from surface (m)") +
  ggtitle("Bhs Podzol: 42") +
  theme_bw() +
  facet_wrap(facets = "Well", nrow = 3, scales = "free") 

```

```{r}



```

